version: '2'

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
  geo_api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
